/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * manager.java
 *
 * Created on 2011-06-09, 20:36:36
 */
package javablock.flowchart.generator;

import config.global;
import java.util.*;
import javablock.Sheet;
import javablock.flowchart.Flowchart;
import javablock.flowchart.JBlock;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author razi
 */
public class Manager extends javax.swing.JPanel {
    private static HashMap<String, Class<Generator>> generators=new HashMap<String, Class<Generator>>();
    public static void addGenerator(String name, Class<Generator> c){
        generators.put(name, c);
    }
    /** Creates new form manager */
    public Manager() {
        initComponents();
        for(String name: generators.keySet()){
            gen.addItem(name);
        }
    }
    String getGenerator(){
        return gen.getSelectedItem().toString();
    }
    public static JBlock[] get(Flowchart f){
        Manager m=new Manager();
        int o=JOptionPane.showConfirmDialog(global.Window, m, "Generator", JOptionPane.OK_CANCEL_OPTION);
        if(o==JOptionPane.OK_OPTION){
            String g=m.getGenerator();
            if(g.equals("For"))
                return new For().get(f);
            if(g.equals("Switch"))
                return new Switch().get(f);
            try{
                return generators.get(g).newInstance().get(f);
            }catch(Exception e){JOptionPane.showMessageDialog(global.Window,
                    "Error\n"+e.getMessage());
            }
        }
        return null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        gen = new javax.swing.JComboBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("config/lang/lang"); // NOI18N
        jLabel1.setText(bundle.getString("manager.generator")); // NOI18N

        gen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "For", "Switch" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gen, 0, 139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox gen;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
