/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Switch.java
 *
 * Created on 2011-06-09, 20:10:47
 */
package javablock.flowchart.generator;

import config.*;
import javablock.Sheet;
import javablock.flowchart.Flowchart;
import javablock.flowchart.JBlock;
import javablock.flowchart.blocks.*;
import javax.swing.JOptionPane;

/**
 *
 * @author razi
 */
class Switch extends javax.swing.JPanel implements Generator {

    /** Creates new form Switch */
    public Switch() {
        initComponents();
    }

    static int decWidth=130;
    @Override
    public JBlock[] get(Flowchart f) {
        Switch g=this;
        int res=JOptionPane.showConfirmDialog(global.Window, g, 
                translator.get("generator.switch.title"),
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if(res==JOptionPane.OK_OPTION){
            String cases[]=this.cases.getText().split("\n");
            JBlock list[]=new JBlock[cases.length*2+4];
            int i=0;
            jumpBlock jump=(jumpBlock) JBlock.make(JBlock.Type.JUMP, f);
            jump.setPos(0,-100);
            list[i++]=jump;
            
            decBlock d1, d2;
            d1=(decBlock) JBlock.make(JBlock.Type.DECISION, f);
            d1.setCode(var.getText()+" = "+cases[0]);
            d1.setPos(0,0);
            jump.connectTo(d1);
            cases[0]="";
            list[i++]=d1;
            int j=1;
            jumpBlock j1, j2;
            j1=(jumpBlock) JBlock.make(JBlock.Type.JUMP, f);
            j1.setPos(0, 100);
            list[i++]=j1;
            d1.connectTo(j1);
            for(String c:cases){
                if(c.length()==0) continue;
                d2 = (decBlock) JBlock.make(JBlock.Type.DECISION, f);
                if(global.pascalMode)
                    d2.setCode(var.getText()+" = "+c);
                else
                    d2.setCode(var.getText()+" == "+c);
                d2.setPos(j*decWidth, 0);
                list[i++]=d2;
                j2=(jumpBlock) JBlock.make(JBlock.Type.JUMP, f);
                j2.setPos(j*decWidth, 100);
                d2.connectTo(j2);
                d1.connectTo(d2);
                j2.connectTo(j1);
                list[i++]=j2;
                d1=d2;
                j1=j2;
                j++;
            }
            jumpBlock last=j1;
            j1=(jumpBlock) JBlock.make(JBlock.Type.JUMP, f);
            j1.setPos(j*decWidth, 0);
            j2=(jumpBlock) JBlock.make(JBlock.Type.JUMP, f);
            j2.setPos(j*decWidth, 100);
            d1.connectTo(j1);
            j1.connectTo(j2);
            j2.connectTo(last);
            list[i++]=j1;
            list[i++]=j2;
            return list;
        }
        return null;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        var = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cases = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("config/lang/lang"); // NOI18N
        jLabel1.setText(bundle.getString("generator.switch.variable")); // NOI18N

        cases.setColumns(2);
        cases.setRows(1);
        jScrollPane1.setViewportView(cases);

        jLabel2.setText(bundle.getString("generator.switch.cases")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(var, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(var, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(113, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cases;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField var;
    // End of variables declaration//GEN-END:variables

    
}
